# TODO: Security context for envoy
# TODO: add resource requests and limits to envoy
# TODO: add documentation for this new architecture of headless clients
apiVersion: apps/v1
kind: Deployment
...
spec:
...
    spec:
      affinity: {}
      containers:
      - env:
        - name: STAKATER_ARMA3_ENVOY_BABOON_CONFIGMAP
          value: b99ad6af14f13b0d755cb16e3b539c01d367907c
        image: envoyproxy/envoy:v1.24-latest
        imagePullPolicy: IfNotPresent
        name: sidecar
        ports:
        - containerPort: 2502
          name: 2502udp
          protocol: UDP
        - containerPort: 2503
          name: 2503udp
          protocol: UDP
        - containerPort: 2504
          name: 2504udp
          protocol: UDP
        - containerPort: 2505
          name: 2505udp
          protocol: UDP
        - containerPort: 2506
          name: 2506udp
          protocol: UDP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/envoy
          name: envoy-config
          readOnly: true
...
      volumes:
      - configMap:
          defaultMode: 420
          name: arma3-baboon
        name: config
      - name: data
        persistentVolumeClaim:
          claimName: arma3-baboon-data
      - name: profile
        persistentVolumeClaim:
          claimName: arma3-baboon-profile
      - configMap:
          defaultMode: 420
          name: arma3-baboon-modpresets
        name: modpresets
      - configMap:
          defaultMode: 420
          name: arma3-baboon-scripts
        name: scripts
      - configMap:
          defaultMode: 420
          name: arma3-envoy-baboon
        name: envoy-config
      - emptyDir:
          medium: Memory
        name: tmp
      - emptyDir:
          medium: Memory
        name: rsyncd
      - emptyDir: {}
        name: home
      - emptyDir: {}
        name: steamcmd