{{- if .Values.headlessclient.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "arma3.fullname" . }}-headlessclient
data:
  # TODO The profile name == the container name
  {{ .Values.headlessclient.name }}.Arma3Profile: |-
    battleyeLicense=1;
    version=1;
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "arma3.fullname" . }}-headlessclient-env
data:
  ARMA_LIMITFPS: "100"
  {{- with .Values.config.env }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}