{{- if .Values.headlessclient.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "arma3.fullname" . }}-headlessclient
  labels:
    {{- include "arma3.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports: []
  clusterIP: None
  selector: {}
{{- end }}