{{- if (include "rsyncEnabled" .) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "arma3.fullname" . }}-rsyncd
  labels:
    {{- include "arma3.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - name: rsync
      port: 873
      targetPort: 8873
      protocol: TCP
  selector:
    {{- include "arma3.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: server
{{- end }}