{{- if .Values.headlessclient.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "arma3.fullname" . }}-tunnel
  labels:
    {{- include "arma3.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
    - name: udp-1
      port: 2302
      targetPort: 2302
      protocol: UDP
    - name: udp-2
      port: 2303
      targetPort: 2303
      protocol: UDP
    - name: upd-3
      port: 2304
      targetPort: 2304
      protocol: UDP
    - name: upd-4
      port: 2305
      targetPort: 2305
      protocol: UDP
    - name: upd-5
      port: 2306
      targetPort: 2306
      protocol: UDP
  selector:
    {{- include "arma3.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: server
  sessionAffinity: None
  type: ClusterIP
{{- end }}