replicas: null

# automatically trigger a deployment update on configmap or secret changes
deploymentAnnotations:
  reloader.stakater.com/auto: "true"

# expose the service using metallb
service:
  type: LoadBalancer
  loadbalancerIP: 192.168.178.3
  annotations:
    metallb.universe.tf/allow-shared-ip: share-192.168.178.3

# set server resources
resources:
  limits:
    cpu: 4
    memory: 8Gi
  requests:
    cpu: 2
    memory: 6Gi

config:
  hostname: arma3.example.com
  headlessClients:
    - 127.0.0.1

  battleeye: 0
  env:
    STEAM_BRANCH: creatordlc
    ARMA_CDLC: vn
    MODS_PRESET: "/modpresets/antistasi.html"

persistence:
  data:
    enabled: true
    storageClass: disk
    accessMode: ReadWriteOnce
    size: 100Gi

  headlessclient:
    enabled: true
    storageClass: nfs
    accessMode: ReadWriteMany
    size: 100Gi

  profile:
    enabled: true
    storageClass: disk
    accessMode: ReadWriteOnce
    size: 2Gi

# set HC resources
headlessclient:
  replicas: null
  resources:
    limits:
      cpu: 4
      memory: 3Gi
    requests:
      cpu: 500m
      memory: 2Gi

# set tunnel (envoy) resources
tunnel:
  resources:
    limits:
      cpu: 250m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi

# set rsync resources
rsync:
  resources:
    limits:
      cpu: 250m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi