replicas: null

deploymentAnnotations:
  reloader.stakater.com/auto: "true"

# 1. Headless Client IP Pool
podAnnotations:
  cni.projectcalico.org/ipv4pools: '["arma3.game-servers"]'

service:
  type: LoadBalancer
  loadbalancerIP: 192.168.178.3
  annotations:
    metallb.universe.tf/allow-shared-ip: share-192.168.178.3

resources:
  limits:
    cpu: 4
    memory: 8Gi
  requests:
    cpu: 2
    memory: 6Gi

config:
  hostname: arma3.example.com
  headlessClients:
    # List of bare metal cluster nodes
    - 192.168.178.4
    - 192.168.178.5
    - 192.168.178.6

  battleeye: 0
  env:
    STEAM_BRANCH: creatordlc
    ARMA_CDLC: vn
    MODS_PRESET: "/modpresets/antistasi.html"

persistence:
  data:
    enabled: true
    storageClass: longhorn
    accessMode: ReadWriteOnce
    size: 100Gi

  headlessclient:
    enabled: true
    storageClass: longhorn
    accessMode: ReadWriteMany
    size: 100Gi

  profile:
    enabled: true
    storageClass: longhorn-crypto
    accessMode: ReadWriteOnce
    size: 2Gi

headlessclient:
  replicas: null
  resources:
    limits:
      cpu: 4
      memory: 3Gi
    requests:
      cpu: 500m
      memory: 2Gi

rsync:
  resources:
    limits:
      cpu: 250m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi